version: "3.9"
services:
  mock-gcp-cas:
    image: mock-github:0.0.1-mocks
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy-mocks
    container_name: mock-github
    hostname: mock-github
    entrypoint: /usr/local/bin/mock-github
    command: "-port 9000"
  ada-demo:
    image: ada-demo:0.0.1
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: ada-demo
    hostname: ada-demo
    environment:
      - GIT_PLATFORM_URL=http://mock-github:9000
      - PORT=8000
  integration-tests:
    image: integration-tests:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy-mocks
    container_name: integration-tests
    entrypoint: /usr/local/bin/integration-tests
    environment:
      - API_URL=http://ada-demo:8000
    depends_on:
      - ada-demo
      - mock-gcp-cas
